name: Pago Profesores - WebApp - Build Validation

on:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  build: 
    uses: letymsft/github-reusable-workflows/.github/workflows/reusable-app-service-build.yml@main
    with:
      ENVIRONMENT: development
    secrets: inherit